reorder_imports = true
reorder_modules = true

# Automatically fix deprecated style.
use_field_init_shorthand = true
use_try_shorthand = true

# unstable features
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
# format_code_in_doc_comments = true
