[package]
name = "cw-tee-mtcs"
version = "0.1.0"
edition = "2021"
authors = ["Informal Systems <hello@informal.systems>"]
exclude = ["contract.wasm", "hash.txt"]

[[bin]]
name = "schema"
path = "bin/schema.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
library = []
mock-sgx = ["quartz-common/mock-sgx-cw"]

[dependencies]
# external
hex = { version = "0.4.3", default-features = false }
k256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
schemars = "0.8.15"
sha2 = "0.10.8"
serde_json = "1.0.117"
thiserror = { version = "1.0.49" }

# cosmwasm
cosmwasm-schema = { version = "2.1.1", default-features = false }
cosmwasm-std = { version = "2.1.1", default-features = false, features = ["std", "abort"] }
cw-storage-plus = { version = "2.0.0", default-features = false }
cw20-base = { version = "2.0.0", features = ["library"] }
cw20 = "2.0.0"
cw2 = "2.0.0"

# quartz
quartz-common = { path = "../../../../core/quartz-common", features = ["contract"] }

# patch indirect deps
getrandom = { version = "0.2.15", features = ["js"] }

[dev-dependencies]
cosmwasm-schema = "2.1.1"
cw-multi-test = "2.1.0"
serde_json = "1.0.113"
