[package]
name = "cw-tee-mtcs"
version = "0.1.0"
edition = "2021"

exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
# external
getrandom = { version = "0.2", features = ["js"] }
hex = { version = "0.4.3", default-features = false }
k256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
schemars = "0.8.15"
serde = { version = "1.0.189", default-features = false, features = ["derive"] }
sha2 = "0.10.8"
serde_json = "1.0.117"
thiserror = { version = "1.0.49" }

# cosmwasm
cosmwasm-schema = "1.5.0"
cosmwasm-std = { version = "1.5.0", features = ["cosmwasm_1_3"] }
cw-storage-plus = "1.1.0"
cw20-base = { version = "1.1.1", features = ["library"] }
cw20 = "1.1.1"
cw2 = "1.1.1"

# quartz
quartz-cw = { path = "../../../../cosmwasm/packages/quartz-cw" }

[dev-dependencies]
cw-multi-test = "0.17.0"
serde_json = "1.0.113"
