[package]
name = "tcbinfo-msgs"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# external

# cosmos
cosmwasm-schema.workspace = true
