mock_sgx = false
tx_sender = "admin"
chain_id = "testing"
node_url = "127.0.0.1:25567"
enclave_rpc_addr = "http://127.0.0.1"
enclave_rpc_port = 11090
trusted_hash = ""
trusted_height = 0
release = true
