[package]
name = "quartz-cw-prover"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["command-line-utilities", "cryptography::cryptocurrencies", "wasm"]
keywords = ["cosmos", "cosmwasm", "cycles", "quartz", "sgx"]
readme = "README.md"
description = """
CLI to generate a merkle proof of a key in the state of a CosmWasm contract.
"""

[dependencies]
# external
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true

# cosmos
cosmrs.workspace = true
tendermint.workspace = true
tendermint-rpc.workspace = true

# quartz
quartz-cw-proof.workspace = true

[dev-dependencies]
hex.workspace = true
