[package]
name = "quartz-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quartz-cw.workspace = true
quartz-proto.workspace = true
quartz-enclave.workspace = true
cosmrs = { version = "0.16.0"}
color-eyre = { version = "0.6.2", default-features = false }
clap = { version = "4.1.8", default-features = false, features = ["derive", "std"] }
tendermint-light-client = { version = "=0.36.0", default-features = false, features = ["rust-crypto"] }
