name: "transfers"

services:
  node:
    container_name: wasmd
    build: "./wasmd"
    ports:
      - "26657:26657"
      - "26656:26656"
      - "1317:1317"
  enclave:
    container_name: quartz-cli-2
    environment:
      DOCKER_BUILDKIT: 1
    build:
      context: ".."
      dockerfile: "./cli/Dockerfile"
      ssh:
        - default
    depends_on:
      - node
