name: "transfers"

volumes:
  data:

services:
  node:
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:1317/cosmos/base/tendermint/v1beta1/blocks/1",
        ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - data:/root/.neutrond
    build:
      context: "./neutrond"
    network_mode: host
  # enclave:
  #   environment:
  #     DOCKER_BUILDKIT: 1
  #   build:
  #     context: ".."
  #     dockerfile: "./crates/cli/Dockerfile"
  #   depends_on:
  #     node:
  #       condition: service_healthy
  #   ports:
  #     - "11090:11090"
  #   volumes:
  #     - data:/root/.neutrond
  #     - ../examples/transfers:/opt/examples/transfers
