name: "transfers"

volumes:
  data:

services:
  node:
    container_name: neutron
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:1317/cosmos/base/tendermint/v1beta1/blocks/1",
        ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - data:/root/.neutrond
    build:
      context: "./neutrond"
    network_mode: host
  enclave:
    container_name: enclave
    environment:
      DOCKER_BUILDKIT: 1
      ADMIN_SK: 07b291dca4ead76392945ea0a8c35b2d506617d36337788c9043c8fc992213e1
    build:
      context: ".."
      dockerfile: "./crates/cli/Dockerfile"
    depends_on:
      node:
        condition: service_healthy
    volumes:
      - data:/root/.neutrond
    network_mode: host
