name: "transfers"

volumes:
  wasmd_data:

services:
  node:
    container_name: wasmd
    build: "./wasmd"
    ports:
      - "26657:26657"
      - "26656:26656"
      - "1317:1317"
    network_mode: host
    volumes:
      - wasmd_data:/root/.wasmd

  enclave:
    container_name: quartz-cli-transfers
    environment:
      DOCKER_BUILDKIT: 1
    build:
      context: ".."
      dockerfile: "./crates/cli/Dockerfile"
    depends_on:
      - node
    ports:
      - "11090:11090"
    network_mode: host
    volumes:
      - wasmd_data:/root/.wasmd
