[package]
name = "quartz-print-fmspc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
keywords = ["blockchain", "cosmos", "tendermint", "cycles", "quartz"]
readme = "README.md"
description = """
"""

[dependencies]
dcap-qvl = "0.1.0"
hex.workspace = true
serde_json.workspace = true
tokio.workspace = true
