[template]
description = "An functioning example of a quartz app"

ignore = [
    "contracts/Cargo.lock",
    "frontend/package-lock.json",
    "frontend/public/images",
    "target/",  
    "contracts/target",
    "enclave/target",
]