mock_sgx = true
tx_sender = "admin"
chain_id = "testing"
node_url = "143.244.186.205:26657"
enclave_rpc_addr = "http://127.0.0.1"
enclave_rpc_port = 11090
trusted_height = 334196
trusted_hash = "934AC18E4E5438D30EAE6F9003DFAF455B3C3A2AB40A990E73ACDE52FEDAB70A"
release = false
