[package]
name = "quartz-dcap-verifier-msgs"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["cosmos", "cosmwasm", "cycles", "quartz", "sgx"]
readme = "README.md"
description = """
"""

[dependencies]
# cosmos
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
