[package]
name = "quartz-dcap-verifier-msgs"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["blockchain", "cosmos", "tendermint", "cycles", "quartz"]
readme = "README.md"
description = """
"""

[dependencies]
# cosmos
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
