[package]
name = "quartz-tee-ra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.4.0"
cosmwasm-std = "1.4.0"
hex-literal = "0.4.1"
num-bigint = "0.4.4"
serde_json = "1.0.108"
sha2 = "0.10.8"
thiserror = { version = "1.0.49" }

der = { version = "0.7.9", default-features = false }
displaydoc = { version = "0.2.4", default-features = false }
mc-sgx-core-types = { git = "https://github.com/informalsystems/sgx" }
mc-sgx-dcap-types = { git = "https://github.com/informalsystems/sgx" }
mc-sgx-dcap-sys-types = { git = "https://github.com/informalsystems/sgx" }
mc-attestation-verifier = { git = "https://github.com/informalsystems/attestation" }
serde = { version = "1.0.198", default-features = false }
x509-cert = { version = "0.2.5", default-features = false }
zeroize = { version = "1.7.0", default-features = false }
