[package]
name = "quartz-tee-ra"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["blockchain", "cosmos", "cosmwasm", "cycles", "quartz"]
readme = "README.md"

[features]
default = []
dcap = [
    "dep:mc-attestation-verifier",
    "dep:mc-sgx-core-types",
    "dep:mc-sgx-dcap-types",
    "dep:mc-sgx-dcap-sys-types"
]

[dependencies]
# external
der.workspace = true
displaydoc.workspace = true
hex-literal.workspace = true
num-bigint.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
x509-cert.workspace = true
x509-parser.workspace = true
zeroize.workspace = true
# mobilecoin
mc-attestation-verifier = { workspace = true, optional = true }
mc-sgx-core-types = { workspace = true, optional = true }
mc-sgx-dcap-types = { workspace = true, optional = true }
# mc-sgx-dcap-sys-types = { workspace = true, optional = true }
mc-sgx-dcap-sys-types = { version = "0.11.0", workspace = true, optional = true }

# cosmos
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true

[dev-dependencies]
hex = "0.4.3"
