[package]
name = "transfers_contracts"
version = "0.1.0"
edition = "2021"

exclude = ["contract.wasm", "hash.txt"]

[[bin]]
name = "schema"
path = "bin/schema.rs"


[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true


[dependencies]
# external
sha2 = "0.10.8"
serde_json = "1.0.117"
thiserror = { version = "1.0.49" }
getrandom = { version = "0.2.15", features = ["js"] }

mio = "1.0.0"

cw-utils = "2.0.0"
cw2 = "2.0.0"
cw20-base = { version = "2.0.0", features = ["library"] }

cosmwasm-schema = { version = "2.0.0", default-features = false }
cosmwasm-std = { version = "2.0.0", default-features = false , features = ["std"] }
cw-storage-plus = { version = "2.0.0", default-features = false}
# cosmwasm-vm = "2.0.0"

region = "=3.0.2"
# corosensei = "0.1.4"
# wasmer = "^4.2.6"

# quartz
quartz-cw = { path = "../../../cosmwasm/packages/quartz-cw" }

