[package]
name = "quartz-cw"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["blockchain", "cosmos", "cosmwasm", "cycles", "quartz"]
readme = "README.md"

[features]
default = []
mock-sgx = []
std = ["k256/std", "serde/std", "serde_json/std", "sha2/std", "cosmwasm-std/std"]

[dependencies]
# external
k256 = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
sha2 = { workspace = true, default-features = false }
thiserror = { workspace = true, default-features = false }

# cosmos
cw-storage-plus = { workspace = true, default-features = false }
cosmwasm-schema = { workspace = true, default-features = false }
cosmwasm-std = { workspace = true, default-features = false }

# quartz
quartz-tee-ra = { workspace = true, default-features = false }

[dev-dependencies]
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
