mock_sgx = false
tx_sender = "val1"
chain_id = "pion-1"
node_url = "https://rpc-falcron.pion-1.ntrn.tech"
ws_url = "wss://rpc-falcron.pion-1.ntrn.tech/websocket"
grpc_url = "https://grpc-falcron.pion-1.ntrn.tech:80"
# node_url = "https://neutron-testnet-rpc.polkachu.com"
# ws_url = "wss://neutron-testnet-rpc.polkachu.com/websocket"
# grpc_url = "https://grpc.baryon.remedy.tm.p2p.org:443"
enclave_rpc_addr = "https://127.0.0.1"
enclave_rpc_port = 11091
trusted_hash = ""
trusted_height = 0
release = true
