name: E2E tests
on: [push]  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node for frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          check-latest: true

      - name: Run containers wasmd and enclave
        run:
          docker compose -f docker/docker-compose.yml up -d --build

      - name: Wait for handshake completion
        timeout-minutes: 25
        run: |
          while ! docker logs quartz-cli-transfers 2>&1 | grep -q "Handshake complete:"; do
            echo "Waiting for handshake completion..."
            sleep 15
          done

      - name: Capture logs from wasmd container
        id: capture_logs
        working-directory: apps/transfers/frontend
        run: docker logs quartz-cli-transfers > quartz-cli-transfers_logs.txt

      - name: Setup environment variables
        working-directory: apps/transfers/frontend
        run: cp .env.example .env.local

      - name: Extract contract address and public key
        id: extract_vars
        run: |
          echo "CONTRACT_ADDRESS=$(grep 'Contract Address:' apps/transfers/frontend/quartz-cli-transfers_logs.txt | awk '{print $NF}')" >> $GITHUB_OUTPUT
          echo "PUBKEY=$(grep 'Handshake complete:' apps/transfers/frontend/quartz-cli-transfers_logs.txt | awk '{print $NF}')" >> $GITHUB_OUTPUT

      - name: Debug - Print extracted variables
        run: |
          echo "Extracted CONTRACT_ADDRESS: ${{ steps.extract_vars.outputs.CONTRACT_ADDRESS }}"
          echo "Extracted PUBKEY: ${{ steps.extract_vars.outputs.PUBKEY }}"

      - name: Setup environment variables
        working-directory: apps/transfers/frontend
        run: |
          cp .env.example .env.local
          sed -i "s/^NEXT_PUBLIC_TRANSFERS_CONTRACT_ADDRESS=.*/NEXT_PUBLIC_TRANSFERS_CONTRACT_ADDRESS=${{ steps.extract_vars.outputs.CONTRACT_ADDRESS }}/" .env.local
          sed -i "s/^NEXT_PUBLIC_ENCLAVE_PUBLIC_KEY=.*/NEXT_PUBLIC_ENCLAVE_PUBLIC_KEY=${{ steps.extract_vars.outputs.PUBKEY }}/" .env.local

      - name: Print .env.local contents
        working-directory: apps/transfers/frontend
        run: cat .env.local

      - name: Install dependencies for the frontend
        working-directory: apps/transfers/frontend
        run: npm ci

      - name: Run all E2E tests
        working-directory: apps/transfers/frontend
        run: npm run test
