name: Frontend
on:
  pull_request:
    paths:
      - .github/workflows/frontend.yml
      - apps/transfers/frontend/**
defaults:
  run:
    working-directory: apps/transfers/frontend
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          check-latest: true
      - run: npm ci
      - run: npm run lint
