[package]
name = "enclave"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[[bin]]
name = "encrypt"
path = "bin/encrypt.rs"




[dependencies]
# external
hex = { version = "0.4.3", default-features = false }
k256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
schemars = "0.8.15"
# mio = "1.0.0"

thiserror = { version = "1.0.49" }
tonic = { version = "0.11.0"}
cosmrs = { version = "0.16.0"}

serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.117", default-features = false }

ecies = { version = "0.2.3", default-features = false, features = ["pure"] }
clap = { version = "4.1.8", default-features = false, features = ["derive", "std"] }
tokio = { version = "1.38.0", default-features = false, features = ["macros", "rt-multi-thread", "rt"] }
tendermint = { version = "=0.36.0", default-features = false }
tendermint-light-client = { version = "=0.36.0", default-features = false, features = ["rust-crypto"] }
color-eyre = { version = "0.6.2", default-features = false }
prost = { version = "0.12.3", default-features = false }
anyhow ={ version = "*" }
sha2 = "0.10.8"

cosmwasm-schema = { version = "2.0.0", default-features = false }
cosmwasm-std = { version = "2.0.0", default-features = false , features = ["std"] }
cw-storage-plus = { version = "2.0.0", default-features = false}



# local
transfers_contracts = { path = "../contracts" }

# quartz
quartz-cw = { path = "../../../cosmwasm/packages/quartz-cw" }
quartz-proto = { path = "../../../core/quartz-proto" }
quartz-enclave = { path = "../../../core/quartz"}

[dev-dependencies]
cw-multi-test = "2.0.0"
# serde_json = "1.0.117"
# cosmwasm-vm = "2.0.0"

[build-dependencies]
tonic-build = "0.11.0"

