[package]
name = "quartz-app-transfers-enclave"
version = "0.1.0"
edition = "2021"
authors = ["Informal Systems <hello@informal.systems>"]
default-run = "quartz-app-transfers-enclave"

[[bin]]
name = "encrypt"
path = "bin/encrypt.rs"

[features]
mock-sgx = ["quartz-cw/mock-sgx", "quartz-enclave/mock-sgx"]

[dependencies]
# external
anyhow.workspace = true
clap.workspace = true
color-eyre.workspace = true
ecies.workspace = true
hex.workspace = true
k256.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true

# cosmos
cosmrs.workspace = true
cosmwasm-std.workspace = true
tendermint.workspace = true
tendermint-light-client.workspace = true

# quartz
cycles-sync.workspace = true
quartz-cw.workspace = true
quartz-proto.workspace = true
quartz-enclave.workspace = true
transfers-contract.workspace = true

[build-dependencies]
tonic-build.workspace = true
